# Generated by Django 2.2.4 on 2019-08-30 13:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20190830_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], default='u', max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('u', 'unknown')], default='u', max_length=2),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('l', 'liked'), ('d', 'disliked')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], max_length=7),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('u', 'unknown')], max_length=10),
        ),
    ]
