# Generated by Django 2.2.4 on 2019-09-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0005_auto_20190830_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pugorugh.UserPref'),
        ),
    ]
