# Generated by Django 2.2.4 on 2019-09-06 16:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0008_auto_20190906_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], default='m,f', max_length=5),
        ),
    ]
