# Generated by Django 2.2.4 on 2019-09-13 13:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0011_auto_20190910_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('l', 'liked'), ('d', 'disliked'), ('u', 'unknown')], max_length=1),
        ),
    ]
